StarLabsm/ForProject

CMakeLists.txt

Feat squash 3

---

CMakeLists.txt

feat(test): update 1 (#24)

---

.mergify.yml

feat(docs): update mergify.yml

---

scripts/stonedb_build.sh

fix(scripts):add aaa to stonedb_build.sh #49

---

scripts/stonedb_build.sh

feat(script):test two commit

---

.github/mergify.yml_bak

feat(cicd):test squash

---

scripts/stonedb_build.sh

fix(stonedb):change scripts

---

.github/mergify.yml

feat(cicd):add queue

---

scripts/stonedb_build.sh

fix(scripts): delete zsp and add asdf

---

scripts/stonedb_build.sh

fix(scripts):add 123
fix(scripts):add 456

fix(script):delete asdf

---

.github/mergify.yml

fix(mergify):remove squaue

---

scripts/stonedb_build.sh

fix(script):pr change stoendb_build.sh

---

scripts/stonedb_build.sh

fix(test):test11111

---

scripts/stonedb_build.sh

feat(script):add  test pr1

---

Doxyfile-perfschema

Thanks for test docs and ci/cd.
Issue Number: close #33

docs(schema): delete one line #33

---

scripts/stonedb_build.sh

fix(script):test pr1-1

---

.github/mergify.yml
.github/workflows/integration-compile-mtr.yml

feat(mergify):add change label

---

scripts/stonedb_build.sh

feat(scripts): spz rebase test_1

---

scripts/stonedb_build.sh

fix test : sp merge test2

---

mysql-test/t/alias.test

fix(mtr):test1

---

mysql-test/t/alias.test

fix(tt):tt2

---

mysql-test/t/alias.test

feat(a):aa
